version: "3"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  sentinel:
    container_name: sentinel
    build: mock-sentinel
    ports:
      - 26379:26379